include: package:lint/strict.yaml

linter:
  rules:
    unawaited_futures: true
    always_use_package_imports: false
    sort_pub_dependencies: false
    use_setters_to_change_properties: false
    unreachable_from_main: false
    avoid_print: false
