name: example
description: A repository of examples on working with `Cardoteka`.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cardoteka:
    path: '../../cardoteka'
  flutter_riverpod: ^2.4.9
  riverpod: ^2.4.9
  bloc: ^8.1.2
  meta: ^1.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^2.2.0

flutter:
  uses-material-design: true