include: package:lint/package.yaml

analyzer:
  exclude:
    - 'example/**'

linter:
  rules:
    unawaited_futures: true
    discarded_futures: true
    always_use_package_imports: false
    sort_pub_dependencies: false
