include: package:lints/recommended.yaml

analyzer:
  exclude:
    - "packages/cardoteka/test/**" # todo(13.12.2025, @PackRuble): temp
    - "example/**" # todo(13.12.2025, @PackRuble): temp

linter:
  rules:
    unawaited_futures: true
    discarded_futures: true
    always_use_package_imports: false
    sort_pub_dependencies: false
    curly_braces_in_flow_control_structures: false
    document_ignores: false
