name: cardoteka
description: The best type-safe wrapper over SharedPreferences.
  For what?
  ▶ store strongly typed key-value
  ▶ get access to get/modify only by typed key
  ▶ be able to work with null values
  ▶ have a wiretap
version: 0.2.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.1.1 # next release contains min dart SDK = 2.18

  # A project that was created and uses flutter 3.0.0 has a flutter_test package that depends on meta 1.7.0
  # Therefore, when upgrading the version of this package, you need to take this into account.
  meta: ^1.7.0

dev_dependencies:

  flutter_test:
    sdk: flutter

  # These dependencies can be as up-to-date as the currently installed flutter version allows.
  riverpod: ^2.4.9
  lint: ^2.2.0

screenshots:
  - description: 'Well met! I am pleased to present a type-safe wrap over SP'
    path: res/cardoteka_banner.png

funding:
  - https://t.me/+AkGV73kZi_Q1YTMy