name: cardoteka
description: The best type-safe wrapper over SharedPreferences.
  For what?
  ▶ store strongly typed key-value
  ▶ get access to get/modify only by typed key
  ▶ be able to work with null values
  ▶ have a wiretap
version: 0.2.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.0
  meta: ^1.9.1

dev_dependencies:

  flutter_test:
    sdk: flutter

  riverpod: ^2.3.6
  lint: ^2.1.2

screenshots:
  - description: 'Well met! I am pleased to present a type-safe wrap over SP'
    path: res/cardoteka_banner.png

funding:
  - https://t.me/+AkGV73kZi_Q1YTMy