name: cardoteka
description: The best type-safe wrapper over SharedPreferences.
  Why so?
  -> strongly typed cards for access to storage
  -> use get|set
  -> can work with nullable values
  -> callback based updates

homepage: https://t.me/+AkGV73kZi_Q1YTMy
repository: https://github.com/PackRuble/cardoteka
issue_tracker: https://github.com/PackRuble/cardoteka/issues

version: 1.1.0

environment:
  sdk: ^3.1.0

dependencies:
  flutter:
    sdk: flutter

  # 2.2.3 release contains min dart SDK = 3.1.0
  # next release contains min dart SDK = 3.3.0
  shared_preferences: ^2.2.3

  # version is clearly related to the minimum version of the dart sdk
  meta: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^2.2.0

screenshots:
  - description: 'Cardoteka is a better type-safe wrapper over SharedPreferences.'
    path: res/cardoteka_banner.png

funding:
  - https://t.me/+AkGV73kZi_Q1YTMy

topics:
  - shared-preferences
  - storage
  - cardoteka
  - database
  - persistence
