name: reactive_db # todo: rename cardoteka
description: A reactive db with handy use - wrapper of shared preferences. # todo
version: 0.2.0

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  shared_preferences: ^2.1.0
  meta: ^1.8.0 # change after bump flutter_test

dev_dependencies:
  flutter_test:
    sdk: flutter

  riverpod: ^2.3.4
  lint: ^2.0.1
