name: cardoteka
description: The best type-safe wrapper over SharedPreferences.
  Why so?
  -> strongly typed cards for access to storage
  -> use get|set
  -> can work with nullable values
  -> callback based updates

homepage: https://t.me/+AkGV73kZi_Q1YTMy
repository: https://github.com/PackRuble/cardoteka
issue_tracker: https://github.com/PackRuble/cardoteka/issues

version: 1.0.0

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.1.1 # next release contains min dart SDK = 2.18
  # A project that was created and uses flutter 3.0.0 has a flutter_test package that depends on meta 1.7.0
  # Therefore, when upgrading the version of this package, you need to take this into account.
  meta: ^1.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^2.2.0

screenshots:
  - description: 'Cardoteka is a better type-safe wrapper over SharedPreferences.'
    path: res/cardoteka_banner.png

funding:
  - https://t.me/+AkGV73kZi_Q1YTMy

topics:
  - shared-preferences
  - storage
  - cardoteka
  - database
  - persistence
