name: cardoteka_repo
publish_to: none

environment:
  sdk: ^3.6.0

workspace:
  - packages/cardoteka
  - packages/cardoteka_sp
  - packages/cardoteka_json

dev_dependencies:
  lint_rules_for_dart:
    path: ../lint_rules_for_dart