name: cardoteka
description: The best type-safe wrapper over SharedPreferences.
  Why so?
  -> strongly typed cards for access to storage
  -> use get|set
  -> can work with nullable values
  -> callback based updates

homepage: https://t.me/+AkGV73kZi_Q1YTMy
repository: https://github.com/PackRuble/cardoteka
issue_tracker: https://github.com/PackRuble/cardoteka/issues

version: 2.0.0

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  # dart sdk limitation matches - ^3.5.0
  shared_preferences: ^2.5.2

  # version is clearly related to the minimum version of the dart sdk
  meta: ^1.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^2.6.1

  # [[shared_preferences] Remove legacy testing section from README · Issue #153108 · flutter/flutter](https://github.com/flutter/flutter/issues/153108#issuecomment-2278510439)
  shared_preferences_platform_interface: any

screenshots:
  - description: 'Cardoteka is a better type-safe wrapper over SharedPreferences.'
    path: res/cardoteka_banner.png

funding:
  - https://t.me/+AkGV73kZi_Q1YTMy

topics:
  - shared-preferences
  - storage
  - cardoteka
  - database
  - persistence
