name: reactive_db # card_db? kartoteka_db
description: A reactive db with handy use - wrapper of shared preferences.
version: 0.1.1

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  shared_preferences: ^2.1.0
  meta: ^1.8.0 # change after bump flutter_test

dev_dependencies:
  flutter_test:
    sdk: flutter

  riverpod: ^2.3.4
  lint: ^2.0.1
