name: cardoteka_json
description: Json files for Cardoteka.

homepage: https://t.me/+AkGV73kZi_Q1YTMy
repository: https://github.com/PackRuble/cardoteka
issue_tracker: https://github.com/PackRuble/cardoteka/issues

version: 0.0.1

environment:
  sdk: ^3.6.0

resolution: workspace

dependencies:
  cardoteka:
    version: ^3.0.0-dev.0
# todo(29.03.2026, @PackRuble): for local development
#    path: ../cardoteka

# task(30.03.2026, @PackRuble): [[cross_file] Platform-aware factories. · Issue #91869 · flutter/flutter](https://github.com/flutter/flutter/issues/91869)
#  cross_file:
#    git:
#      url: https://github.com/bparrishMines/packages.git
#      path: packages/cross_file/cross_file
#      ref: new_crossfile

  meta: 1.17.0

dev_dependencies:
  test: ^1.26.3

screenshots:
  - description: 'Cardoteka is a better type-safe wrapper over SharedPreferences.'
    path: ../../res/cardoteka_banner.png

funding:
  - https://t.me/+AkGV73kZi_Q1YTMy

topics:
  - json
  - storage
  - cardoteka
  - database
  - persistence
