name: Project testing and upload coverage reports to Codecov

on:
  workflow_dispatch:

  push:
    tags:
      - '**' # when any tags are pushed

jobs:
  dart_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - run: flutter --version
      - run: flutter pub get
      - run: flutter test --coverage

  codecov_report:
    runs-on: ubuntu-latest
    needs: dart_test

    steps:
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}